<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ZXing.Net" Version="0.16.9" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.12" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\BarcodeRenamer2\AppConfig.cs" Link="AppConfig.cs" />
    <Compile Include="..\BarcodeRenamer2\FileItem.cs" Link="FileItem.cs" />
    <Compile Include="..\BarcodeRenamer2\BarcodeRecognitionService.cs" Link="BarcodeRecognitionService.cs" />
  </ItemGroup>

</Project>
